# Generated by Django 4.0.5 on 2022-06-22 20:24

from django.db import migrations, models
import instaapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0011_alter_postfilecontent_file_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilecontent',
            name='file',
            field=models.FileField(upload_to=instaapp.models.user_directory_path),
        ),
    ]
