# Generated by Django 4.0.5 on 2022-06-22 22:58

from django.db import migrations, models
import instaapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0015_alter_postfilecontent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='instaapp.tag'),
        ),
        migrations.AlterField(
            model_name='postfilecontent',
            name='file',
            field=models.FileField(upload_to=instaapp.models.user_directory_path),
        ),
    ]
