# Generated by Django 4.0.5 on 2022-06-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0028_alter_postfilecontent_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.DeleteModel(
            name='PostFileContent',
        ),
    ]
